services:
  - type: web
    name: archinthai
    runtime: static
    buildCommand: "cd auth && npm install && npm run build"
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /auth/assets/*
        destination: /auth/dist/assets/*
      - type: rewrite
        source: /auth/
        destination: /auth/dist/index.html
      - type: rewrite
        source: /auth
        destination: /auth/dist/index.html
      - type: rewrite
        source: /creator
        destination: /creator.html
